### 什么是同步异步
 - 同步：代码从上往下依次执行，如果一个地方卡住了，下面的代码就不执行
 - 异步：会虽然从上往下依次执行，如果一个地方卡住了，是不会阻止代码向下执行的    定时器、所有的事件、promise

 ### 事件调用
   把任务交给了事件引擎(所有的js事件全部都是异步的)

 ### 什么是事件循环

 - js先执行主线程的代码，如果主线程有异步代码，比如定时器，promise,或者事件那么会把异步代码放到异步队列中存储，当异步代码的条件成立的时候，把异步代码压入到主线程中去执行，(压入的方式是如果有微任务，就先执行微任务，执行完微任务再执行宏任务，)当主线程空间的时候执行压入的代码，执行完之后再从异步队列中压入异步代码到主线程，这个过程叫事件循环。

 - 注意的是执行完微任务是第一层的，如果在宏任务中开个微任务，那么先执行宏任务，再执行宏任务中的微任务
  ```
  setTimeout(()=>{
      promise();
  })
  ```

  - 异步的操作是不容易进行维护开发的，同步操作才有利于维护开发(上面的代码执行完才会执行下面的，有序的)

  ### promise

  - promise是解决异步编程顺序问题(也就是说，让异步的代码同步执行)

  - 为什么要用promise?
      + promise解决了异步编程的问题
      + 在then里面就走'同步'
  - 如何使用promise?
      ```
      new Promise(function(resolve,reject){
          这个是主线程
          当异步代码执行完，通过异步代码结果去调用resolve或者reject
          异步代码有可能报错或者错误，如果报错或者错误
          一般都是resolve
      })
      它有一个返回值，返回值是promise对象，这个对象有then方法
      ``` 
    + then方法
        then(成功函数，失败函数)

        第一个then(微任务)
            成功函数里面的参数就是异步的结果

        第二个then(微任务)
            第一个then的返回值
        
        then如果不是函数就穿透，直到是函数为止
   - 虽然promise解决了异步编程的问题，但是在then的外面还是异步的

   - then中包含了两个参数都是函数，第一个函数是成功之后的回调，第二个函数是失败之后的回调

   - finally：不管成功还是失败都会进这个回调函数

   - try catch
   如果代码有可能会报错，下面的代码是不会执行的，如果使用try,catch那么try中的代码报错会进入catch,报错是不会影响后面代码的执行的
      try{

      }catch(e){

      }
### fetch
   ```
    fetch().then(function(d){
        return d.json();
    }).then(function(d){
            console.log(d)//d就是d.json()
    })

    当进入到第一个then的时候，d就是返回的数据，但是这个数据是被promise包裹了一层  d.json()->'[]'->[]

    JSON->长的像对象和数组的字符串，本质是字符串

     '[]'JSON -> []数组
     '{}'JSON ->{}对象

     JSON取值不方便的，可以使用JSON.parse(),把JSON转成对象

     parse必须为标准的JSON格式才成功转换
     '{"name":"zf"}'
     '[]'->[],

     对象转JSON->JSON.stringify()的副作用是函数和undefined会被过滤掉  [] -> '[]'
   ```

   ### promise.all

- Promise.all 接收一个 promise 对象的数组作为参数，当这个数组里的所有 promise 对象全部变为resolve或有 reject 状态出现的时候，它才会去调用 .then 方法,它们是并发执行的。

- Promise.all可以将多个Promise实例包装成一个新的Promise实例。同时，成功和失败的返回值是不同的，成功的时候返回的是一个结果数组，而失败的时候则返回最先被reject失败状态的值。
    ```
    let p1 = new Promise((resolve, reject) => {
  resolve('成功了')
        })

    let p2 = new Promise((resolve, reject) => {
       resolve('success')
    })

    let p3 = Promse.reject('失败')

    Promise.all([p1, p2]).then((result) => {
  console.log(result)  //['成功了','success']                  
    }).catch((error) => {
  console.log(error)
    })

    Promise.all([p1,p3,p2]).then((result) => {
  console.log(result)
    }).catch((error) => {
      console.log(error)      // 失败了，打出 '失败'
    })

    ```
- 需要特别注意的是，Promise.all获得的成功结果的数组里面的数据顺序和Promise.all接收到的数组顺序是一致的，即p1的结果在前，即便p1的结果获取的比p2要晚。这带来了一个绝大的好处：在前端开发请求数据的过程中，偶尔会遇到发送多个请求并根据请求顺序获取和使用数据的场景，使用Promise.all毫无疑问可以解决这个问题。

### promise.race
  - Promse.race就是赛跑的意思，意思就是说，Promise.race([p1, p2, p3])里面哪个结果获得的快，就返回那个结果，不管结果本身是成功状态还是失败状态。

  ```
  let p1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  },1000)
   })

   let p2 = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject('failed')
  }, 500)
    })

   Promise.race([p1, p2]).then((result) => {
  console.log(result)
    }).catch((error) => {
  console.log(error)  // 打开的是 'failed'
    })
  ```
### catch
 - //throw 抛出异常，说明代码错误，会进catch，如果是return new Error('error!!!')不会进catch

 - then或catch的返回值不能是promise本身否则会造成死循环

